# Generated by Django 5.2.7 on 2026-05-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='correo electrónico')),
                ('success', models.BooleanField(default=False, verbose_name='éxito')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='dirección IP')),
            ],
            options={
                'verbose_name': 'Intento de inicio de sesión',
                'verbose_name_plural': 'Intentos de inicio de sesión',
                'ordering': ['-timestamp'],
            },
        ),
    ]
