# Generated by Django 5.2.13 on 2026-06-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordRecovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='correo electrónico')),
                ('code', models.CharField(max_length=6, unique=True, verbose_name='código')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('is_used', models.BooleanField(default=False, verbose_name='utilizado')),
            ],
            options={
                'verbose_name': 'Recuperación de contraseña',
                'verbose_name_plural': 'Recuperaciones de contraseña',
                'ordering': ['-created_at'],
            },
        ),
    ]
