# Generated by Django 5.2.7 on 2026-05-11 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='correo electrónico')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='teléfono')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='dirección')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='fecha de registro')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='fecha de sesión')),
                ('objetivo', models.CharField(max_length=255, verbose_name='objetivo')),
                ('avance', models.TextField(blank=True, verbose_name='avance')),
                ('activo', models.BooleanField(default=True, verbose_name='activa')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='princpal.paciente')),
            ],
            options={
                'verbose_name': 'Sesión',
                'verbose_name_plural': 'Sesiones',
                'ordering': ['-fecha'],
            },
        ),
    ]
