# Generated by Django 6.0.5 on 2026-06-03 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('princpal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_dolor', models.IntegerField(default=1)),
                ('pregunta1', models.CharField(max_length=255)),
                ('pregunta2', models.TextField()),
                ('pregunta3', models.CharField(max_length=255)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
