# Generated by Django 5.2.13 on 2026-08-26 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('princpal', '0002_diagnostico'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254, verbose_name='correo del usuario')),
                ('video_id', models.CharField(max_length=32, verbose_name='ID del video')),
                ('category', models.CharField(max_length=100, verbose_name='categoría')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de visualización')),
            ],
            options={
                'verbose_name': 'Video visto',
                'verbose_name_plural': 'Videos vistos',
                'ordering': ['-viewed_at'],
            },
        ),
    ]
