# Generated by Django 5.2.13 on 2026-08-26 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('princpal', '0003_videoview'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoview',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='rutina completada'),
        ),
    ]
