# Generated by Django 5.2.13 on 2026-08-26 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('princpal', '0004_videoview_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoview',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha de finalización'),
        ),
    ]
