# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('princpal', '0005_videoview_completed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='título')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('level', models.CharField(default='Principiante', max_length=50, verbose_name='nivel')),
                ('category', models.CharField(default='General', max_length=100, verbose_name='categoría')),
                ('file', models.FileField(upload_to='videos/', verbose_name='archivo de video')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de carga')),
            ],
            options={
                'verbose_name': 'Video local',
                'verbose_name_plural': 'Videos locales',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]