# Generated by Django 5.2.13 on 2026-10-06 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crear_cuenta', '0005_usuario_desactivar_animaciones_usuario_tamano_letra'),
        ('princpal', '0010_paciente_edad_zona_afectada'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostico',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnostico', to='crear_cuenta.usuario', verbose_name='usuario'),
        ),
    ]
