# Generated by Django 5.2.14 on 2026-08-28 01:54:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crear_cuenta', '0002_usuario_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='modo_oscuro',
            field=models.BooleanField(default=False, verbose_name='modo oscuro'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('paciente', 'Paciente'), ('doctor', 'Doctor')], default='paciente', max_length=20, verbose_name='rol'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='especialidad',
            field=models.CharField(blank=True, max_length=150, verbose_name='especialidad'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='colegiado',
            field=models.CharField(blank=True, max_length=80, verbose_name='número de colegiado'),
        ),
    ]
