# Generated by Django 6.1 on 2026-10-03 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crear_cuenta', '0003_usuario_modo_oscuro'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='teléfono'),
        ),
    ]
