# Generated by Django 6.1 on 2026-10-04 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crear_cuenta', '0004_usuario_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='desactivar_animaciones',
            field=models.BooleanField(default=False, verbose_name='animaciones desactivadas'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tamano_letra',
            field=models.CharField(choices=[('normal', 'Normal'), ('large', 'Grande'), ('xlarge', 'Muy grande')], default='normal', max_length=10, verbose_name='tamaño de letra'),
        ),
    ]
